---
title: "Wild Bootstrap Simulation Result"
author: "Zhipeng"
date: "March 10, 2017"
output: pdf_document
---

#Technique Details of Wild bootstrap algorithm.

a) choice of distributions used to perturb the residuals, 
 
 Both two-point distribution (Rademacher distribution) and six-point distribution (from Webb's Reworking Wild Bootstrap Based Inference for Clustered Errors) are implemented in function roub_Wild().
 
b) form of correction to the residuals. 
 
 MBB adjustment matrix from Professor Tipton's paper: Small Sample Adjustment for Robust Variance Estimation With Meta-Rgression.
 
 This is the default of robumeta package.
 
c) what version of RVE to use in calculating the test statistic.
 
 t-test with small sample correction on both v-cov matrices and degrees of freedom.
 
d) whether to use residuals based on a restricted model or from the full model. 
 
 Restricted model.
 
I used full model at first, but it does not perform very well. It tends to over-reject when null hypothesis is true. 
 
 \pagebreak

# Single covariate model with different degrees of freedom (corrected).

The single covariate in the model is a categorical variable. It's distribution is changed to get different degrees of freedom values.

Number of groups m = 20

Number of SMDs in each group k = 5

Pre-group sample size n = 30

Correction of outcomes r = .5

Isq = 1/3  

Number of replications of each bootstrap procedure: 1000.

Number of simulation datasets: 200. (This decides the precision of error rate calculation. Maximum precision is 1/200 = 0.005)


    
## two-point distribution


|                                 | df =2.19  | 2.79 | 4.64 | 4.66  | 6.78  | 9.45  |
|---------------------------------|-----------|------|------|-------|-------|-------|
| Wild Bootstrap Error Rate       | 0.135     | 0.13 | 0.09 | 0.06  | 0.08  | 0.045 |
| CRVE (fixed weights) Error Rate | 0         | 0.05 | 0.06 | 0.035 | 0.055 | 0.04  |


```{r,echo = F, message= F, warning=FALSE}
library(ggplot2)
result_df <- as.data.frame(cbind(df = c(2.19, 2.79, 4.64,4.66, 6.78, 9.45,2.19, 2.79, 4.64,4.66, 6.78, 9.45), 
                                 error_rate = c(0.135,0.13, 0.09, 0.06, 0.08, 0.045,0, 0.05,0.06,0.035,0.055, 0.04),
                                 algorithm = c(rep(c(1,0), each = 6))))

result_df[result_df$algorithm == 1,3]<- "Wild bootstrap"
result_df[result_df$algorithm == 0,3]<- "CRVE"
ggplot(result_df, aes(x = df, y = error_rate, colour = algorithm)) + 
  geom_path()+
  theme_bw() +
  geom_hline(yintercept = 0.05,linetype  = 4, size = .4)+
  theme(axis.line = element_line(colour = "black"),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank())



```


## six-point distribution


|                                 | df =1.25 | 2.72 | 4.61  | 4.7 | NA | NA |
|---------------------------------|----------|------|-------|----|----|----|
| Wild Bootstrap Error Rate       | 0.13     | 0.09 | 0.06  | 0.065 | NA | NA |
| CRVE (fixed weights) Error Rate | 0        | 0.03 | 0.035 | 0.04 | NA | NA |

\pagebreak

# Single covariate model with different covariate type

X1a: 0,1 categorical variable. unbalanced

X2a: 0,1 categorical variable. balanced

X3a: numeric variable, balanced

X4a: numeric variable, balanced

X5.10: numeric variable, skewed

Number of SMDs in each group k = 10

Number of simulation datasets: 80. (This decides the precision of error rate calculation. Maximum precision is 1/80 = 0.0125)

Other parameters are identical to the previous section. 


## Without small sample correction + fixed weights
(df = 18, uncorrected)

|                                 | X1a   | X2a    | X3a    | X4a    | X5.10  |
|---------------------------------|-------|--------|--------|--------|--------|
| Wild Bootstrap Error Rate       | 0.125 | 0.05   | 0.025  | 0.0625 | 0.1875 |
| CRVE (fixed weights) Error Rate | 0.15  | 0.0375 | 0.0375 | 0.05   | 0.175  |

## With small sample correction + fixed weights

|                                 | X1a(df = 2.77) | X2a(13.7) | X3a(9.41) |  X4a(16.6) | X5.10(2.42) |
|---------------------------------|--------|--------|--------|------|--------|
| Wild Bootstrap Error Rate       | 0.1    | 0.0375 | 0.0125 | 0.05 | 0.2    |
| CRVE (fixed weights) Error Rate | 0.0375 | 0.0375 | 0.0125 | 0.05 | 0.0125 |

## With small sample correction + "CORR" weights

|                                 | X1a (df = 2.75) | X2a(13.5) | X3a(9.5) |  X4a(16.5) | X5.10(2.44) |
|---------------------------------|-----------------|----------------|---------------|-----------------|------------------|
| Wild Bootstrap Error Rate       | 0.1             | 0.0375         | 0.025         | 0.0625          | 0.2              |
| CRVE (CORR weights) Error Rate | 0.0375          | 0.0375         | 0.0125        | 0.05            | 0.0125           |
